### PR TITLE
(SURV EDIT ME) NicheToolbox Patches

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Color at XY is broken in full screen and is inverted. Working on fixing....

Edit:
I fixed inverting issues. However the fullscreen issue still exists, i left it in unfinished...maybe you can fix it?

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
i will merge this as soon as i can get on 👍
________________________________
From: SharkPool-SP ***@***.***>
Sent: Thursday, October 12, 2023 1:28 AM
To: SurvExe1Pc/unsafe-extensions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SurvExe1Pc/unsafe-extensions] NicheToolbox Patches (PR #1)


Color at XY is broken in full screen and is inverted. Working on fixing....

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/SurvExe1Pc/unsafe-extensions/pull/1

Commit Summary

  *   b4bdab4<https://github.com/SurvExe1Pc/unsafe-extensions/pull/1/commits/b4bdab4f4c36e76450303f62562ff8e991dc41c8> NicheToolbox Patches

File Changes

(1 file<https://github.com/SurvExe1Pc/unsafe-extensions/pull/1/files>)

  *   M extensions/0znzw/NicheToolbox.js<https://github.com/SurvExe1Pc/unsafe-extensions/pull/1/files#diff-2478ed805718f5ec6d47ad19cce39c7d0538aa4c4c95fd4052d6e58c21bbef7d> (11)

Patch Links:

  *   https://github.com/SurvExe1Pc/unsafe-extensions/pull/1.patch
  *   https://github.com/SurvExe1Pc/unsafe-extensions/pull/1.diff

**Comment by SurvExe1Pc** [comment]
i cant request changes the normal way so:
(requested changes):
LN 153 In Pull 1 File NicheToolbox.js:
  remove "console.log(canvas);" please.
________________________________
From: SharkPool-SP ***@***.***>
Sent: Thursday, October 12, 2023 1:28 AM
To: SurvExe1Pc/unsafe-extensions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SurvExe1Pc/unsafe-extensions] NicheToolbox Patches (PR #1)


Color at XY is broken in full screen and is inverted. Working on fixing....

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/SurvExe1Pc/unsafe-extensions/pull/1

Commit Summary

  *   b4bdab4<https://github.com/SurvExe1Pc/unsafe-extensions/pull/1/commits/b4bdab4f4c36e76450303f62562ff8e991dc41c8> NicheToolbox Patches

File Changes

(1 file<https://github.com/SurvExe1Pc/unsafe-extensions/pull/1/files>)

  *   M extensions/0znzw/NicheToolbox.js<https://github.com/SurvExe1Pc/unsafe-extensions/pull/1/files#diff-2478ed805718f5ec6d47ad19cce39c7d0538aa4c4c95fd4052d6e58c21bbef7d> (11)

Patch Links:

  *   https://github.com/SurvExe1Pc/unsafe-extensions/pull/1.patch
  *   https://github.com/SurvExe1Pc/unsafe-extensions/pull/1.diff

**Comment by SharkPool-SP** [comment]
> i cant request changes the normal way so: (requested changes): LN 153 In Pull 1 File NicheToolbox.js: remove "console.log(canvas);" please.
> […](#)

No, I need it there cuz it’s unfinished. I fixed the mirroring issue and I started fixing the full screen thing but I didn’t finish. I need u to cuz ur smarter

**Comment by SurvExe1Pc** [comment]
why do you need more? what is not working cause
________________________________

**Comment by SharkPool-SP** [comment]
> why do you need more? what is not working cause
> […](#)

i need it for debugging. Remove it for final version..... I'm just saying the fullscreen detection is broken

**Comment by SurvExe1Pc** [comment]
what about fullscreen, i have not found a fullscreen bug, please give more detail
________________________________

**Comment by SharkPool-SP** [comment]
> what about fullscreen, i have not found a fullscreen bug, please give more detail
> […](#)

color detection is offset when the project is in fullscreen, put a rainbow and detect the colors, its offset

**Comment by SurvExe1Pc** [comment]
hm?
________________________________

**Comment by SurvExe1Pc** [comment]
thats not our problem though, its a problem with scratch itself
________________________________

**Comment by SurvExe1Pc** [comment]
OH SHI- YOUR RIGHT
________________________________

**Comment by SurvExe1Pc** [comment]
I have no idea why it is offset in Fullscreen, if possible, could you ask Garbo what could be going on?, and also, I have some other changes to besides the fixes you made.
________________________________

**Comment by SurvExe1Pc** [comment]
FYI the offset is there due to the fact that it grabs from the top left corner so it must offset it to be "scratch coordinates" with your changes the x and y must be "240x, -180y" to get the center.
________________________________

**Comment by SurvExe1Pc** [comment]
ok so I made a project to scan the entire screen with the block and the offsets are so weird!, here is the data I collected:

no fullscreen editor:
  -17
  -6
no fullscreen project:
  -17
  -6
editor fullscreen:
  161
  -145
project fullscreen:
  161
  -145
zoomed out fullscreen project:
  out of range? (like its out of the "scratch canvas bounds or -240 to 240")
  out of range? (like its out of the "scratch canvas bounds or -180 to 180")
________________________________

**Comment by SurvExe1Pc** [comment]
fyi by "editor" and "project" I mean "fullscreened project in the editor" and "fullscreened project on project page/homepage"
________________________________

**Comment by SurvExe1Pc** [comment]
here is my scanner! (if it doesn't show then f I have to do it over email, first time sending a file to github over email fyi)
________________________________

**Comment by SurvExe1Pc** [comment]
HEY DID YOU ASK YET??
also here is a beta version of my progress so far.
https://load-ing.pages.dev/NicheToolbox/NicheToolbox_v1.3b1690388702.js

________________________________

**Comment by SurvExe1Pc** [comment]
i just reverse engineered the "extractColor" function cause i could not get on github xd.

________________________________

**Comment by SurvExe1Pc** [comment]
This will be worked on, I have a beta version up.

**Pull request closed without merging**
